# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-Common-profanity_us
version:      1.5
version_from: lib/Regexp/Profanity/US.pm
installdirs:  site
requires:
    Regexp::Common:                2.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
